<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="cuarm">
  <!-- math constants -->
  <xacro:property name="pi" value="3.1415926535897931" />
  <!-- staubli geometry files are in millimeters -->
  <xacro:property name="staubli_scale" value="0.001 0.001 0.001" />

  <!-- named paths -->
  <xacro:property name="staubli_geom_path" value="/home/armuser/ros/trajectory_planner/models"/>


  <!-- link macro -->
  <xacro:macro name="link_macro" params="link_name link_num origin">
    <link name="${link_name}">      
    <visual>
      <geometry>
	${origin}
	<mesh filename="file:${staubli_geom_path}/staubli_${link_num}.dae" scale="${staubli_scale}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
	${origin}
	<mesh filename="file:${staubli_geom_path}/staubli_${link_num}.dae" scale="${staubli_scale}"/>
      </geometry>
    </collision>
  </link>
  </xacro:macro>

    <!-- Colors -->
    <xacro:macro name="color_blue">
        <material name="blue">
            <color rgba="0 0 0.75 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_yellow">
        <material name="yellow">
            <color rgba="0.75 0.75 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_red_green">
        <material name="red_green">
            <color rgba="1.0 1.0 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_black">
        <material name="black">
            <color rgba="0.1 0.1 0.1 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_dark_gray">
        <material name="dark_gray">
            <color rgba="0.3 0.3 0.3 1.0" />
        </material>
    </xacro:macro>
    
    <xacro:macro name="color_gray">
        <material name="gray">
            <color rgba="0.5 0.5 0.5 1.0" />
        </material>
    </xacro:macro>
    
    <xacro:macro name="color_silver">
        <material name="silver">
            <color rgba="0.9 0.9 0.9 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_green">
        <material name="green">
            <color rgba="0 0.75 0.1 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_olive">
        <material name="olive">
            <color rgba="0.5 0.5 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_orange">
        <material name="orange">
            <color rgba="1.0 0.65 0 1.0" />
        </material>
    </xacro:macro>
    
    <xacro:macro name="color_aqua">
        <material name="aqua">
            <color rgba="0.25 0.3 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_dark_purple">
        <material name="dark_purple">
            <color rgba="0.3 0 0.3 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_magenta">
        <material name="magenta">
            <color rgba="1.0 0 1.0 0.5" />
        </material>
    </xacro:macro>
    
    <!-- useful macros -->
    <xacro:macro name="prism" params="name x y z *color">
        <link name="${name}">
            <visual>
                <geometry>
                    <box size="${x} ${y} ${z}" />
                </geometry>
                <xacro:insert_block name="color" />
            	<origin rpy="0 0 0" xyz="0 0 ${z/2}" />
            </visual>
            <collision>
                <geometry>
                    <box size="${x} ${y} ${z}" />
                </geometry>
            	<origin rpy="0 0 0" xyz="0 0 ${z/2}" />
            </collision>
        </link>
    </xacro:macro>

    <xacro:macro name="cyl" params="name radius length *color">
        <link name="${name}">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                <xacro:insert_block name="color" />
            	<origin rpy="0 0 0" xyz="0 0 ${length/2}" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
            	<origin rpy="0 0 0" xyz="0 0 ${length/2}" />
            </collision>
        </link>
    </xacro:macro>

    <xacro:cyl name="base_link" radius="0.02" length="0.0">
        <xacro:color_gray />
    </xacro:cyl>

    <joint name="base_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="base_box" />
    </joint>

    <xacro:prism name="base_box" x="0.14" y="0.20" z="0.085">
        <xacro:color_yellow />
    </xacro:prism>

    <joint name="base_rotate" type="revolute">
        <origin xyz="0.025 0 0.085" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <parent link="base_box" />
        <child link="carbon_fiber_link" />
        <limit lower="-1.57" upper="1.57" velocity="0.3" effort="1.0" />
    </joint>

    <xacro:cyl name="carbon_fiber_link" radius=".02" length="0.14">
        <xacro:color_dark_gray />
    </xacro:cyl>

    <joint name="fixed_link_to_elbow" type="fixed">
        <origin xyz="0 0 0.14" rpy="0 0 0" />
        <parent link="carbon_fiber_link" />
        <child link="elbow_link_vertical" />
    </joint>

    <xacro:prism name="elbow_link_vertical" x="0.1" y="0.1" z="0.2">
        <xacro:color_yellow />
    </xacro:prism>

    <joint name="fixed_elbow_internal" type="fixed">
        <origin xyz="0 0.05 0.10" rpy="0 0 0" />
        <parent link="elbow_link_vertical" />
        <child link="elbow_link_horizontal" />
    </joint>

    <xacro:prism name="elbow_link_horizontal" x="0.1" y="0.2" z="0.1">
        <xacro:color_blue />
    </xacro:prism>

    <joint name="elbow_lift" type="revolute">
        <origin xyz="0 0.05 0.10" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <parent link="elbow_link_horizontal" />
        <child link="carbon_fiber_link_2" />
        <limit lower="-2.09" upper="0.52" velocity="0.3" effort="1.0" />
    </joint>

    <xacro:cyl name="carbon_fiber_link_2" radius=".02" length="0.10">
        <xacro:color_dark_gray />
    </xacro:cyl>

    <joint name="fixed_link_to_wrist" type="fixed">
        <origin xyz="0 0 0.10" rpy="0 0 0" />
        <parent link="carbon_fiber_link_2" />
        <child link="wrist_base_link" />
    </joint>

    <xacro:prism name="wrist_base_link" x="0.1" y="0.1" z="0.1">
        <xacro:color_yellow />
    </xacro:prism>

    <joint name="wrist_rotate" type="revolute">
        <origin xyz="0 0 0.10" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <parent link="wrist_base_link" />
        <child link="differential_link" />
        <limit lower="-1.57" upper="1.57" velocity="0.3" effort="1.0" />
    </joint>

    <xacro:prism name="differential_link" x="0.1" y="0.1" z="0.15">
        <xacro:color_olive />    
    </xacro:prism>

    <joint name="differential_rotate" type="revolute">
        <origin xyz="0 0 0.105" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <parent link="differential_link" />
        <child link="diff_crossbar" />
        <limit lower="-1.57" upper="1.57" velocity="0.3" effort="1.0" />
    </joint>

    <xacro:prism name="diff_crossbar" x="0.0" y="0.0" z="0.0">
        <xacro:color_olive />
    </xacro:prism>

    <joint name="differential_lift" type="revolute">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <parent link="diff_crossbar" />
        <child link="gripper_connect_link" />
        <limit lower="-1.57" upper="1.57" velocity="0.3" effort="1.0" />
    </joint>

    <xacro:cyl name="gripper_connect_link" radius="0.005" length="0.045">
        <xacro:color_gray />
    </xacro:cyl>

    <joint name="fixed_link_to_gripper" type="fixed">
        <origin xyz="0 0 0.045" rpy="0 0 0" />
        <parent link="gripper_connect_link" />
        <child link="gripper_frame" />
    </joint>

    <xacro:prism name="gripper_frame" x="0.085" y="0.075" z="0.15">
        <xacro:color_yellow />
    </xacro:prism>

    <joint name="fixed_link_to_hand" type="fixed">
        <origin xyz="0 0 0.15" rpy="0 0 0" />
        <parent link="gripper_frame" />
        <child link="gripper_hand" />
    </joint>

    <xacro:cyl name="gripper_hand" radius="0.04" length="0.17">
        <xacro:color_blue />
    </xacro:cyl>
</robot>
